config/routes.rb
Borges::Application.routes.draw do


#  if Rails.env.development?
#    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
#  end


  get "/graphql", to: "graphql#execute"
  post "/graphql", to: "graphql#execute"

  get "/publish", to: "graphql#publish"
  
  resources :text_fragments


  resources :inventory_copy_confirmations do 
    member do
      post :probablyreturned
    end
  end


  resources :inventories do
    member do 
      get :section
      get :bestsellers
      get :owner
      post :fill
      post :fill_books
    end
  end

  resources :event_shifts


  resources :event_staffers do
    get :autocomplete_event_staffer_name, :on => :collection
  end

  get '/events/:id'=> 'events#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :events do 
    get :autocomplete_event_location_title, :on => :collection
  end


  resources :event_locations


  resources :category_title_list_memberships


  resources :sale_order_line_items

 
  resources :sale_orders do
    member do
      post :post
    end
  end

  resources :return_order_line_items

 
  resources :return_orders do
    member do
      post :post
    end

  end



  resources :owners do
    get :autocomplete_owner_name, :on => :collection
  end


  resources :title_category_memberships


  get '/categories/:id'=> 'categories#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :categories do 
    member do 
      get :chart
    end
  end

  resources :post_title_list_links


  resources :post_title_links


  resources :create_post_title_links


  resources :post_categories

  resources :posts

  resources :title_list_memberships


  resources :title_lists do 
    get :autocomplete_title_title, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
  end


  resources :images


#  mount Ckeditor::Engine => '/ckeditor'

  resources :pages  do 
    get :autocomplete_parent_title, :on => :collection
  end


  resources :publishers do 
    member do
      put :merge_editions_from
    end
  end


  resources :customers do 
    get :autocomplete_customer_name, :on => :collection
  end


  resources :distributors do
    member do
      put :merge_orders_from
      get :chart
    end
  end



  resources :invoice_line_items

  get 'invoices/chart' => 'invoices#chart'
  resources :invoices do
    member do
      post :receive
    end
  end


  resources :purchase_order_line_items do 
    member do
      get :hidden_actions 
      put :move_to_purchase_order
      put :copy_to_bucket
      post :cancel
    end
  end

  resources :bucket_line_items do 

    member do
      get :hidden_actions 
      put :copy_to_purchase_order
      put :copy_to_bucket
      put :move_to_bucket
    end
  end



  resources :purchase_orders do 
    member do
      get :hidden_actions 
      post :submit
      post :receive
      post :cancel
      put :smartdestroy
    end
    get :autocomplete_distributor_name, :on => :collection
    resources :purchase_order_line_items
  end

  resources :buckets do 
    member do
      get :hidden_actions 
      put :smartdestroy
    end
    resources :bucket_line_items
  end



  resources :copies do 
    get :autocomplete,:on => :collection
    get :inventory_autocomplete,:on => :collection
    member do
      post :mark_lost
    end

  end


  resources :editions do
    resources :copies
    get :autocomplete,:on => :collection
    get :autocomplete_title_title, :on => :collection
    member do
      get :hidden_actions 
      put :add_to_purchase_order
      put :add_to_title_list
      put :add_to_bucket
      put :add_to_category
      get :bookshop
    end
  end


  resources :contributions do 
    get :autocomplete_author_full_name, :on => :collection
  end

  get 'titles/search' => 'titles#search'
  get '/titles/:id'=> 'titles#redirector',  :constraints => { :id => /[0-9]+/ }

  resources :titles do 
    get :autocomplete_publisher_name, :on => :collection
    get :autocomplete_distributor_name, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
    get :autocomplete_category_name, :on => :collection

  end


  
  get 'authors/search' => 'authors#search'
  get '/authors/:id'=> 'authors#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :authors

  resources :shopping_carts do
    collection do
      post :garbagecollect
    end
    member do
      post :complete
      post :toggle_pulled
      post :toggle_sold_through
      post :toggle_shipped
      post :toggle_picked_up
      post :toggle_pickup_notify
      post :toggle_is_preorder
      post :toggle_needs_attention
      post :defer
      post :ship
      post :subscribe
    end
  end

  resources :shopping_cart_line_items do
    member do
      post :split
    end
  end
  
  get '/book/:isbn', :to => 'editions#byisbn'
  get '/book/', :to => 'editions#byisbn'

  get '/orderdump', :to => 'sale_orders#dump'
  get '/dashboard/search', :to => 'dashboard#search'
  get '/dashboard/snipcart', :to => 'dashboard#snipcart'
  get '/dashboard/:action', :to => 'dashboard'
  get '/dashboard/', :to => 'dashboard#index'
  get '/content/', :to => 'dashboard#content'
  get '/sales/', :to => 'dashboard#sales'
  get '/simplesales/', :to => 'dashboard#simplesales'
  get '/losses/', :to => 'dashboard#losses'
  get '/events_calendar', :to => 'events#calendar'
  get '/consignment/', :to => 'dashboard#consignment'
  get '/ownerflow/', :to => 'dashboard#ownerflow'
  get '/purchases_by_date_and_owner/', :to => 'dashboard#purchases_by_date_and_owner'
  get '/inventory_value_by_date_and_owner/', :to => 'dashboard#inventory_value_by_date_and_owner'
  get '/inventory_report_by_owner/', :to => 'dashboard#inventory_report_by_owner'
  get '/daily/', :to => 'dashboard#daily', :as => "daily"
  get '/manage_calendar/', :to => 'dashboard#manage_calendar'
  get '/books/', :to => 'home#books'
  get '/food/', :to => 'home#food'
  get '/comingsoon/', :to => 'home#comingsoon'
  get '/gcl/', :to => redirect("https://www.threadcoffee.com/greenmount-coffee-lab/")
  get '/coffee/', :to => 'home#coffee'
  get '/orderfoodonline/', :to => 'home#orderfoodonline'
  get '/thread/', :to => 'home#thread'
  get '/blog/', :to => 'posts#index'
  get '/about/', :to => 'home#about'
  get '/2640/', :to => 'events#twentysixforty'
  get '/newsletter/', :to => 'home#newsletter'
  get '/promotion/antifa', :to => 'home#promotion'
  get '/pages/about/', :to => 'home#about'
  get '/cart', :to => "shopping_carts#current"
  get '/shopping_cart_success', :to => "shopping_carts#success"
  post '/webhook', :to => "shopping_carts#webhook"
  post "/create_bli_from_webhook", :to => "bucket_line_items#create_from_webhook"
  put '/update_cart', :to => "shopping_carts#update_current"
  put '/create-checkout-session', :to => "shopping_carts#checkout"
  match '/bookfair' => 'event_locations#show',:defaults => {:id => 4}
  authenticated :user do
    root :to=>'home#frontpage' 
  end
  root :to=>'home#frontpage' 

  devise_for :users
  resources :users
end

app/models/distributor.rb
class Distributor < ActiveRecord::Base
  attr_accessible :name, :notes, :our_account_number

#  has_many :copies
#  has_many :editions, :through => :copies
  has_many :invoice_line_items, :through => :invoices
  has_many :copies, :through => :invoice_line_items
  has_many :editions, :through => :copies, :uniq=>true
  has_many :titles, :through => :editions, :uniq=>true
  has_many :purchase_orders
  has_many :invoices
  has_many :return_orders

  def to_s 
    name_and_id
  end

  def name_and_id
    "#{name} (#{id})"
  end



  def merge_stuff_from_distributor(unneeded_distributor_id)
    
    begin
      unneeded_distributor=Distributor.find(unneeded_distributor_id)
    rescue
      unneeded_distributor=nil
    end

    if self.id==unneeded_distributor_id.to_i || unneeded_distributor.nil?
      return false
    end
    
    [:return_orders,:purchase_orders,:invoices].each do |m|
      unneeded_distributor.send(m).each do |e|
        e.distributor = self
        e.save!
      end
    end
    
    if self.our_account_number.blank? && ! unneeded_distributor.our_account_number.blank?
      self.our_account_number=unneeded_distributor.our_account_number
    end

    if self.notes.blank? && ! unneeded_distributor.notes.blank?
      self.notes=unneeded_distributor.notes
    end
    self.save!
    unneeded_distributor.destroy
  end



end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController

  before_filter :authenticate_user! 
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction


  # GET /distributors
  # GET /distributors.json
  def index
    @distributors = Distributor.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @distributors }
    end
  end

  # GET /distributors/1
  # GET /distributors/1.json
  def show
    @distributor = Distributor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @distributor }
    end
  end

  # GET /distributors/new
  # GET /distributors/new.json
  def new
    @distributor = Distributor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @distributor }
    end
  end

  # GET /distributors/1/edit
  def edit
    @distributor = Distributor.find(params[:id])
  end

  # POST /distributors
  # POST /distributors.json
  def create
    @distributor = Distributor.new(params[:distributor])

    respond_to do |format|
      if @distributor.save
        format.html { redirect_to @distributor, notice: 'Distributor was successfully created.' }
        format.json { render json: @distributor, status: :created, location: @distributor }
      else
        format.html { render action: "new" }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /distributors/1
  # PUT /distributors/1.json
  def update
    @distributor = Distributor.find(params[:id])

    respond_to do |format|
      if @distributor.update_attributes(params[:distributor])
        format.html { redirect_to @distributor, notice: 'Distributor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @distributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributors/1
  # DELETE /distributors/1.json
  def destroy
    @distributor = Distributor.find(params[:id])
    if @distributor.purchase_orders.size == 0 && @distributor.return_orders.size == 0 && @distributor.invoices.size == 0 
        @distributor.destroy 
    end
    respond_to do |format|
      format.html { redirect_to distributors_url }
      format.json { head :no_content }
    end
  end

  def merge_orders_from
    @distributor = Distributor.find(params[:id])
    @unneeded_distributor_id=params[:unneeded_distributor_id]
    respond_to do |format|
      if @distributor.merge_stuff_from_distributor(@unneeded_distributor_id)
        format.html { redirect_to @distributor,notice: 'Successfully merged orders and deleted unneeded distributor.' } 
      else
        format.html { redirect_to @distributor,alert: 'I could not make the requested merge.' } 
      end
    end
  end


  def chart
    @distributor = Distributor.find(params[:id])
    @title_info=@distributor.titles.collect {|t| t}.uniq.collect {|t| {:instock=>t.in_stock > 0,:title=>t.title.gsub(/[^0-9a-z ]/i,""),:average_time_on_shelf=>t.average_time_on_shelf,:profit_to_date=>t.net_profit_or_loss.cents/100,:id=>t.id}}
    @instock=@title_info.find_all {|t| t[:instock]}
    @outofstock=@title_info.find_all {|t| ! t[:instock]}

    
    respond_to do |format|
      format.html { render action: "chart" }
    end

  end


  private
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
  def sort_column
    %w[created_at number id].include?(params[:sort]) ? params[:sort] : "created_at"
  end

  

end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/views/distributors/_form.html.erb
<%= form_for @distributor,:html=>{:class=>"form-horizontal"} do |f| %>
  <% if @distributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distributor.errors.count, "error") %> prohibited this distributor from being saved:</h2>

      <ul>
      <% @distributor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= mytextfield(f,:name,:name) %>
  <%= mytextfield(f,:our_account_number,:our_account_number) %>
  <%= mytextarea(f,:notes,:notes,{:size=>"40x5"}) %>    
  <%= mysubmit(f,"Save") %>

<% end %>

app/views/distributors/chart.html.erb
<h1>Average time on shelves vs. profit to date for titles from <%= @distributor.name %></h1>
<button style="float:right" class="btn" onclick="window.myChart.resetZoom();">Reset zoom</button>
<canvas id="myChart" width="100%" height="50%" style="height:80% !important;"></canvas>


2


<script>

   
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'scatter',
    data: {
	instocklabels: [<%=  raw @instock.collect {|t| "'#{t[:title]} [#{t[:id]}]'"}.join(", ") %>],
	instockids: [<%=  raw @instock.collect {|t| t[:id]}.join(", ") %>],
	outofstocklabels: [<%=  raw @outofstock.collect {|t| "'#{t[:title]} [#{t[:id]}]'"}.join(", ") %>],
	outofstockids: [<%=  raw @outofstock.collect {|t| t[:id]}.join(", ") %>],
	datasets: [
	    {label: "Titles in stock",
	     backgroundColor: 'rgba(30,255,30,0.5)',
	     data: [ <%=  raw @instock.collect {|t| "{x: #{t[:average_time_on_shelf]},y: #{t[:profit_to_date]}}"}.join "," %>]},
	    {label: "Titles out of stock",
	     backgroundColor: 'rgba(255,30,30,0.5)',
	    data: [ <%=  raw @outofstock.collect {|t| "{x: #{t[:average_time_on_shelf]},y: #{t[:profit_to_date]}}"}.join "," %>]}
	    
		   
		   ,]
    },
    options: {
	onClick: (evt, item) => {
	    e = item[0];
	    if(e._datasetIndex == 0) {
		window.open("/titles/"+myChart.data.instockids[e._index]);}
	    else{
		window.open("/titles/"+myChart.data.outofstockids[e._index]);}
	},
	plugins: {
            zoom: {
                // Container for pan options
                pan: {
                    // Boolean to enable panning
                    enabled: true,
		    
                    // Panning directions. Remove the appropriate direction to disable 
                    // Eg. 'y' would only allow panning in the y direction
                    mode: 'xy'
                },

                // Container for zoom options
                zoom: {
                    // Boolean to enable zooming
                    enabled: true,
		    drag:true,
                    // Zooming directions. Remove the appropriate direction to disable 
                    // Eg. 'y' would only allow zooming in the y direction
                    mode: 'xy',
                }
            }
        },

	tooltips: {
	    callbacks: {
		label: function(tooltipItem, data) {
		    var label;
		    if(tooltipItem.datasetIndex == 0) {
			label = data.instocklabels[tooltipItem.index];}
		    else {
			label = data.outofstocklabels[tooltipItem.index];
		    }
		    return label;
		}
	    }
	} ,
        scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom',
		scaleLabel: {
		    display: true,
		    labelString: "Days on shelf"
		}
	    }],
	    yAxes: [{
                type: 'linear',
                position: 'left',
		scaleLabel: {
		    display: true,
		    labelString: "Profit to date"
		}
            }]

	    
        }
    }
});
    

</script>

app/views/distributors/edit.html.erb
<h1>Editing distributor</h1>

<%= render 'form' %>

<%= link_to 'Show', @distributor %> |
<%= link_to 'Back', distributors_path %>

app/views/distributors/index.html.erb
<div class="span8">
<h1>Listing distributors</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Our account number</th>
    <th># of Open Orders</th>
    <th># of Orders</th>
    <th># of Invoices</th>
    <th># of Returns</th>
    <th></th>
    <th></th>
  </tr>

<% @distributors.each do |distributor| %>
  <tr>
    <td><%= link_to distributor.name, distributor %></td>
    <td><%= distributor.our_account_number %></td>
    <td><%= distributor.purchase_orders.where(:ordered=>false).length %></td>
    <td><%= distributor.purchase_orders.length %></td>
    <td><%= distributor.invoices.length %></td>
    <td><%= distributor.return_orders.length %></td>
    <td><%= mylinkbutton 'Edit', edit_distributor_path(distributor) , {}, "btn-small" %></td>
    <td>
      <% if distributor.purchase_orders.size == 0 && distributor.return_orders.size == 0 && distributor.invoices.size == 0 %>
        <%= link_to('Destroy', distributor, :method => :delete, :data => { :confirm => 'Are you sure?' },:class=>"btn btn-small btn-warning") if can? :destroy, Distributor %></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>
<div class="span2">

<%= mylinkbutton 'New Distributor', new_distributor_path %>
</div>

app/views/distributors/new.html.erb
<h1>New distributor</h1>

<%= render 'form' %>

<%= link_to 'Back', distributors_path %>

app/views/distributors/show.html.erb
<p id="notice"><%= notice %></p>

<%= mylinkbutton 'Analyze titles for profitability', chart_distributor_path(@distributor), {},"btn-success btn-large" %>

<h1>
  <%= @distributor.name %>
</h1>

<div class="span6">
  <div style="float:right;"><%=  link_to raw("<i class='fa fa-pencil'></i>"), edit_distributor_path(@distributor)   if can? :edit, Distributor %></div>

<p>
  <b>Our account number:</b>
  <%= @distributor.our_account_number %>
</p>

<p>
  <b>Notes:</b>
  <%= @distributor.notes.html_safe rescue "" %>
</p>
</div>
<div class="span6">
<h2>Merge orders from</h2>
<%= nested_form_for(@distributor,:html => {:class=>"form"},:url=>{:action=>:merge_orders_from}) do |f| %>
    <div class="field control-group">
      <%= f.label :merge_orders_from, :class=>"control-label" %>
    <div class="controls">
      <%= autocomplete_field_tag :unneeded_distributor, "", autocomplete_distributor_name_titles_path,:id_element => "#unneeded_distributor_id",  :class=>'a_contribution' %>
      <%= hidden_field_tag :unneeded_distributor_id  %>
    </div>
    </div>

    <%= mysubmit f,"Merge" %>
<% end %>

</div>
</div>
<hr>
<div class="row">
<div class="span6">
<h2>Listing purchase orders</h2>

<%= mylinkbutton 'New Purchase order', new_purchase_order_path(:distributor=>@distributor) %>

<table class="table">
  <tr>
    <th><%= sortable "created_at", "Created" %></th>
    <th><%= sortable "number", "Number" %></th>
    <th>Notes</th>
    <th>Ordered?</th>
    <th>Ordered When</th>
  </tr>

<% @distributor.purchase_orders.order(sort_column + ' ' + sort_direction).each do |purchase_order| %>
  <tr>
    <td><%= purchase_order.created_at.to_formatted_s(:just_date) %></td>
    <td><%= link_to purchase_order.number,purchase_order %></td>
    <td><%= purchase_order.notes %></td>
    <td><span class="label <%= purchase_order.ordered? ? 'label-success' : ''%>"><%= purchase_order.ordered? ? 'Yes' : 'Not yet' %></span></td>
    <td><%= purchase_order.ordered_when.to_formatted_s(:just_date) rescue "-" %></td>
  </tr>
<% end %>
</table>

<h2>Listing returns</h2>

<%= mylinkbutton 'New Return', new_return_order_path(:distributor=>@distributor) %>

<table class="table">
  <tr>
    <th><%= sortable "created_at", "Created" %></th>
    <th><%= sortable "number", "Number" %></th>
    <th>Total</th>
    <th>Posted when</th>
  </tr>
  
  <% @distributor.return_orders.order(sort_column + ' ' + sort_direction).each do |return_order| %>
  <tr>
    <td><%= return_order.created_at.to_formatted_s(:just_date) %></td>
    <td><%= link_to return_order.number,return_order %></td>
    <td><%= return_order.total %></td>
    <td><%= return_order.posted_when.to_formatted_s(:just_date) rescue "-" %></td>
  </tr>
  <% end %>
</table>

</div>
 
<div class="span6">
<h2>Listing invoices</h2>

<%= mylinkbutton 'New Invoice', new_invoice_path(:distributor => @distributor) %>

<table class="table">
  <tr>
    <th><%= sortable "created_at", "Created" %></th>
    <th><%= sortable "id","Our id" %></th>
    <th><%= sortable "number","Vendor Number" %></th>
    <th>Notes</th>
    <th># of books</th>
    <th>Total</th>
    <th>Received?</th>
    <th>Sold to date</th>
    <th>Lost to date</th>
  </tr>

<% @distributor.invoices.order(sort_column + ' ' + sort_direction).each do |invoice| %>
  <tr>
    <td><%= invoice.created_at.to_formatted_s(:just_date) %>
    <td><%= link_to invoice.id,invoice %>
    <td><%= link_to invoice.number,invoice %></td>
    <td><%= invoice.notes %></td>
    <td><%= invoice.total_copies %></td>
    <td><%= invoice.total_cost+invoice.shipping_cost %></td>
    <td><%= invoice.received?  ? invoice.received_when.to_formatted_s(:just_date) : "No" %></td>
    <td><%= invoice.received? ? invoice.sales_to_date : "n/a" %></td>
    <td><%= invoice.received? ? invoice.lost_to_date : "n/a" %></td>
  </tr>
<% end %>
</table>
</div>
<div class="span8">
<h2>Titles we have receieved through this distributor</h2>
  <div class="grid">  
    <% @distributor.titles.order('id desc').each_with_index do |t,i| %>
    <%= render :partial=>'titles/gridtitle', :locals => {:title=>t,:text=>""}%>

        <% if i % 6 == 5 %>
    <div class="clearfix visible-md visible-lg visible-sm visible-xs" ></div>
    <% elsif i % 3 == 2 %>
    <div class="clearfix visible-sm" ></div>
    <% elsif i % 2 == 1 %>
    <div class="clearfix visible-xs" ></div>
    <% end %>


    <% end %>
  </div>


</div>