config/routes.rb
Borges::Application.routes.draw do


#  if Rails.env.development?
#    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
#  end


  get "/graphql", to: "graphql#execute"
  post "/graphql", to: "graphql#execute"

  get "/publish", to: "graphql#publish"
  
  resources :text_fragments


  resources :inventory_copy_confirmations do 
    member do
      post :probablyreturned
    end
  end


  resources :inventories do
    member do 
      get :section
      get :bestsellers
      get :owner
      post :fill
      post :fill_books
    end
  end

  resources :event_shifts


  resources :event_staffers do
    get :autocomplete_event_staffer_name, :on => :collection
  end

  get '/events/:id'=> 'events#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :events do 
    get :autocomplete_event_location_title, :on => :collection
  end


  resources :event_locations


  resources :category_title_list_memberships


  resources :sale_order_line_items

 
  resources :sale_orders do
    member do
      post :post
    end
  end

  resources :return_order_line_items

 
  resources :return_orders do
    member do
      post :post
    end

  end



  resources :owners do
    get :autocomplete_owner_name, :on => :collection
  end


  resources :title_category_memberships


  get '/categories/:id'=> 'categories#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :categories do 
    member do 
      get :chart
    end
  end

  resources :post_title_list_links


  resources :post_title_links


  resources :create_post_title_links


  resources :post_categories

  resources :posts

  resources :title_list_memberships


  resources :title_lists do 
    get :autocomplete_title_title, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
  end


  resources :images


#  mount Ckeditor::Engine => '/ckeditor'

  resources :pages  do 
    get :autocomplete_parent_title, :on => :collection
  end


  resources :publishers do 
    member do
      put :merge_editions_from
    end
  end


  resources :customers do 
    get :autocomplete_customer_name, :on => :collection
  end


  resources :distributors do
    member do
      put :merge_orders_from
      get :chart
    end
  end



  resources :invoice_line_items

  get 'invoices/chart' => 'invoices#chart'
  resources :invoices do
    member do
      post :receive
    end
  end


  resources :purchase_order_line_items do 
    member do
      get :hidden_actions 
      put :move_to_purchase_order
      put :copy_to_bucket
      post :cancel
    end
  end

  resources :bucket_line_items do 

    member do
      get :hidden_actions 
      put :copy_to_purchase_order
      put :copy_to_bucket
      put :move_to_bucket
    end
  end



  resources :purchase_orders do 
    member do
      get :hidden_actions 
      post :submit
      post :receive
      post :cancel
      put :smartdestroy
    end
    get :autocomplete_distributor_name, :on => :collection
    resources :purchase_order_line_items
  end

  resources :buckets do 
    member do
      get :hidden_actions 
      put :smartdestroy
    end
    resources :bucket_line_items
  end



  resources :copies do 
    get :autocomplete,:on => :collection
    get :inventory_autocomplete,:on => :collection
    member do
      post :mark_lost
    end

  end


  resources :editions do
    resources :copies
    get :autocomplete,:on => :collection
    get :autocomplete_title_title, :on => :collection
    member do
      get :hidden_actions 
      put :add_to_purchase_order
      put :add_to_title_list
      put :add_to_bucket
      put :add_to_category
      get :bookshop
    end
  end


  resources :contributions do 
    get :autocomplete_author_full_name, :on => :collection
  end

  get 'titles/search' => 'titles#search'
  get '/titles/:id'=> 'titles#redirector',  :constraints => { :id => /[0-9]+/ }

  resources :titles do 
    get :autocomplete_publisher_name, :on => :collection
    get :autocomplete_distributor_name, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
    get :autocomplete_category_name, :on => :collection

  end


  
  get 'authors/search' => 'authors#search'
  get '/authors/:id'=> 'authors#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :authors

  resources :shopping_carts do
    collection do
      post :garbagecollect
    end
    member do
      post :complete
      post :toggle_pulled
      post :toggle_sold_through
      post :toggle_shipped
      post :toggle_picked_up
      post :toggle_pickup_notify
      post :toggle_is_preorder
      post :toggle_needs_attention
      post :defer
      post :ship
      post :subscribe
    end
  end

  resources :shopping_cart_line_items do
    member do
      post :split
    end
  end
  
  get '/book/:isbn', :to => 'editions#byisbn'
  get '/book/', :to => 'editions#byisbn'

  get '/orderdump', :to => 'sale_orders#dump'
  get '/dashboard/search', :to => 'dashboard#search'
  get '/dashboard/snipcart', :to => 'dashboard#snipcart'
  get '/dashboard/:action', :to => 'dashboard'
  get '/dashboard/', :to => 'dashboard#index'
  get '/content/', :to => 'dashboard#content'
  get '/sales/', :to => 'dashboard#sales'
  get '/simplesales/', :to => 'dashboard#simplesales'
  get '/losses/', :to => 'dashboard#losses'
  get '/events_calendar', :to => 'events#calendar'
  get '/consignment/', :to => 'dashboard#consignment'
  get '/ownerflow/', :to => 'dashboard#ownerflow'
  get '/purchases_by_date_and_owner/', :to => 'dashboard#purchases_by_date_and_owner'
  get '/inventory_value_by_date_and_owner/', :to => 'dashboard#inventory_value_by_date_and_owner'
  get '/inventory_report_by_owner/', :to => 'dashboard#inventory_report_by_owner'
  get '/daily/', :to => 'dashboard#daily', :as => "daily"
  get '/manage_calendar/', :to => 'dashboard#manage_calendar'
  get '/books/', :to => 'home#books'
  get '/food/', :to => 'home#food'
  get '/comingsoon/', :to => 'home#comingsoon'
  get '/gcl/', :to => redirect("https://www.threadcoffee.com/greenmount-coffee-lab/")
  get '/coffee/', :to => 'home#coffee'
  get '/orderfoodonline/', :to => 'home#orderfoodonline'
  get '/thread/', :to => 'home#thread'
  get '/blog/', :to => 'posts#index'
  get '/about/', :to => 'home#about'
  get '/2640/', :to => 'events#twentysixforty'
  get '/newsletter/', :to => 'home#newsletter'
  get '/promotion/antifa', :to => 'home#promotion'
  get '/pages/about/', :to => 'home#about'
  get '/cart', :to => "shopping_carts#current"
  get '/shopping_cart_success', :to => "shopping_carts#success"
  post '/webhook', :to => "shopping_carts#webhook"
  post "/create_bli_from_webhook", :to => "bucket_line_items#create_from_webhook"
  put '/update_cart', :to => "shopping_carts#update_current"
  put '/create-checkout-session', :to => "shopping_carts#checkout"
  match '/bookfair' => 'event_locations#show',:defaults => {:id => 4}
  authenticated :user do
    root :to=>'home#frontpage' 
  end
  root :to=>'home#frontpage' 

  devise_for :users
  resources :users
end

app/models/copy.rb
class Copy < ActiveRecord::Base
  belongs_to :edition, :touch => true
  has_one :title, :through => :edition
  belongs_to :invoice_line_item
  has_one :invoice,:through => :invoice_line_item 
  has_one :sale_order_line_item
  has_one :sale_order,:through => :sale_order_line_item 
  has_one :return_order_line_item
  has_one :return_order,:through => :return_order_line_item 
  belongs_to :owner
  attr_accessible :cost_in_cents, :is_used, :notes, :price_in_cents , :cost, :price, :inventoried_when, :deinventoried_when, :status, :owner,:edition_id,:invoice_line_item_id, :owner_id
  has_many :inventory_copy_confirmations  
  monetize :cost_in_cents, :as => "cost"
  monetize :price_in_cents, :as => "price"

  scope :instock, where("status"=>"STOCK")
  scope :lost, where("status"=>"LOST")
  scope :returned, where("status"=>"RETURNED")
  scope :sold, where("status"=>"SOLD")
  
  after_save :reindex_title

  def info
    "$#{price}" + (notes || is_used? ? " [#{notes} #{'USED' if is_used?}]" : "" )
  end

  def sell(sale_price)
    self.price=sale_price # this comes from the line item
    self.status="SOLD"
    self.deinventoried_when=DateTime.now
    self.save!
  end
  
  def do_return()
    self.status="RETURNED"
    self.deinventoried_when=DateTime.now
    self.save!
  end

  def mark_probablyreturned()
    if self.status=="STOCK"
      self.status="PROBABLYRETURNED"
      self.deinventoried_when=DateTime.now
      self.save!
    end
  end



  def mark_lost()
    if self.status=="STOCK"
      self.status="LOST"
      self.deinventoried_when=DateTime.now
      self.save!
    end
  end

  def confirm(inventory)
    @inventory_copy_confirmation = InventoryCopyConfirmation.new(:copy_id=>self.id,:inventory_id=>inventory.id)
    @inventory_copy_confirmation.status=true
    @inventory_copy_confirmation.save!
  end

  
  def how_long_it_took_to_get
  end

  private 
  def reindex_title 
    self.title.save! # does it reindex?
  end



end

app/controllers/copies_controller.rb
# -*- coding: utf-8 -*-
class CopiesController < ApplicationController
  before_filter :authenticate_user! 
  load_and_authorize_resource
  before_filter :hack_out_params , :only=>[:create,:update]

  # GET /copies
  # GET /copies.json
  def index
    @edition = Edition.find(params[:edition_id])
    @copies = @edition.copies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @copies }
    end
  end

  # GET /copies/1
  # GET /copies/1.json
  def show
    @copy = Copy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @copy }
    end
  end

  # GET /copies/new
  # GET /copies/new.json
  def new
    @copy = Copy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @copy }
    end
  end

  # GET /copies/1/edit
  def edit
    @copy = Copy.find(params[:id])
  end

  # POST /copies
  # POST /copies.json
  def create
    @copy = Copy.new(params[:copy])

    respond_to do |format|
      if @copy.save
        format.html { redirect_to @copy, notice: 'Copy was successfully created.' }
        format.json { render json: @copy, status: :created, location: @copy }
      else
        format.html { render action: "new" }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /copies/1
  # PUT /copies/1.json
  def update
    @copy = Copy.find(params[:id])

    respond_to do |format|
      if @copy.update_attributes(params[:copy])
        format.html { redirect_to @copy, notice: 'Copy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  def mark_lost
    @copy = Copy.find(params[:id])
    @copy.mark_lost()
    respond_to do |format|
      format.js {}
    end
  end
      

  # DELETE /copies/1
  # DELETE /copies/1.json
  def destroy
    @copy = Copy.find(params[:id])
    @copy.destroy

    respond_to do |format|
      format.html { redirect_to copies_url }
      format.json { head :no_content }
    end
  end

  def inventory_autocomplete
    @edition_search=Edition.search do
      fulltext params[:term]
    end
    
    @copies_data=@edition_search.results.collect do |edition|
      @copies=edition.copies.instock.order("price_in_cents desc")
      copies_on_inventory_already= Inventory.find(params[:inventory_id]).copies.collect {|c| c.id}
      @copies=@copies.find_all {|c| !(copies_on_inventory_already.include? c.id)}
      @copies.collect do |copy|
        hash = {"id" => copy.id.to_s, "label" => "#{copy.info}—#{edition.title.title} (#{edition.year_of_publication}) {#{edition.number} #{edition.format}} [#{edition.isbn13}]", "value" => "#{copy.info}—#{edition.title.title} (#{edition.year_of_publication}) {#{edition.number} #{edition.format}} [#{edition.isbn13}]"}
      end
    end
    respond_to do |format|
      format.json { render json: @copies_data.flatten }
    end
    
  end

  def autocomplete
    @edition_search=Edition.search do
      fulltext params[:term]
    end
    
    @copies_data=@edition_search.results.collect do |edition|
      @copies=edition.copies.instock.order("price_in_cents desc")
      # you can't sell a copy someone else is trying to sell!
      copies_on_sale_orders= SaleOrder.where(:posted=>[false,nil]).collect {|so| so.sale_order_line_items.collect {|soli| soli.copy_id}}.flatten

      # you can't sell a copy someone else is trying to return!
      copies_on_return_orders= ReturnOrder.where(:posted=>[false,nil]).collect {|ro| ro.return_order_line_items.collect {|roli| roli.copy_id}}.flatten

      @copies=@copies.find_all {|c| !(copies_on_sale_orders.include? c.id)}
      @copies=@copies.find_all {|c| !(copies_on_return_orders.include? c.id)}

      @copies.collect do |copy|
        hash = {"id" => copy.id.to_s, "label" => "#{copy.info}—#{edition.title.title} (#{edition.year_of_publication}) {#{edition.number} #{edition.format}} [#{edition.isbn13}]", "value" => "#{copy.info}—#{edition.title.title} (#{edition.year_of_publication}) {#{edition.number} #{edition.format}} [#{edition.isbn13}]"}
      end
    end
    respond_to do |format|
      format.json { render json: @copies_data.flatten }
    end
  end



  private
  
  def hack_out_params
    params[:copy].delete :owner
   end

  
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/views/copies/_form.html.erb
<%= nested_form_for(@copy,:html=>{:class=>"form-horizontal"}) do |f| %>
  <% if @copy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copy.errors.count, "error") %> prohibited this copy from being saved:</h2>

      <ul>
      <% @copy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2><%= @copy.edition.title %> <%= @copy.edition %>, Copy #<%= @copy.id %></h2>
  <table class="table">
    <tr><th>Inventoried</th><td><%= @copy.inventoried_when.to_formatted_s(:just_date) rescue "" %></td></tr>
    <tr><th>Deinventoried</th><td><%= @copy.deinventoried_when.to_formatted_s(:just_date) rescue "" %></td></tr>
  </table>
  

  <%= mymoneyfield f,:cost,:cost %>
  <%= mymoneyfield f,:price,:price %>
  <%= mytextarea f,:notes,:notes %> 
  <%= myselectfield f,:owner,:owner,autocomplete_owner_name_owners_path, new_owner_path() %> 
  <%= mycheckbox f,:is_used,:is_used %> 
  <%= mysubmit(f,"Update") %>

<% end %>

app/views/copies/edit.html.erb
<h1>Editing copy</h1>

<%= render 'form' %>

<%= link_to 'Show', @copy %> |
<%= link_to 'Back', copies_path %>

app/views/copies/index.html.erb
<h1>Listing copies</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Edition</th>
    <th>Cost</th>
    <th>Price</th>
    <th>Status</th>
    <th>Owner</th>
    <th>Is used</th>
    <th>Ordered</th>
    <th>Received</th>
    <th>Sold</th>
    <th>Returned or Removed</th>
    <th></th>
    <th></th>
  </tr>

<% @copies.each do |copy| %>
  <tr id="copy_<%= copy.id %>">
    <td><%= link_to copy.title,copy.title %></td>
    <td><%= link_to copy.edition,copy.edition %><br /><%= copy.notes %>
</td>
    <td>$<%= copy.cost %></td>
    <td>$<%= copy.price %></td>
    <td class="copy-status">
      <%= copy.status %>
      <% if copy.status=="STOCK" %>
      <% copy.inventory_copy_confirmations.each do |icc| %>
      <% if icc.status %>
      <br /><small><%= link_to icc.inventory.name,icc.inventory,:style=>"color:green;line-height:16px;" %></small>
      <% end %>
      <% end %>
      <% end %>
    </td>
    <td><%= link_to copy.owner.name_and_id, copy.owner rescue "" %></td>
    <td><%= copy.is_used %></td>
    <td>
      <%= copy.invoice_line_item.purchase_order_line_item.purchase_order.ordered_when.to_formatted_s(:just_date) rescue "" %>
      <br />
      <%= link_to copy.invoice_line_item.purchase_order_line_item.purchase_order.number,copy.invoice_line_item.purchase_order_line_item.purchase_order  rescue "" %><br />
        <%= link_to copy.invoice_line_item.invoice.distributor,copy.invoice_line_item.invoice.distributor unless copy.invoice_line_item.nil? %>
    </td>
    <td>
      <%= copy.invoice_line_item.invoice.received_when.to_formatted_s(:just_date) rescue "" %>
      <br />
      <%= link_to copy.invoice_line_item.invoice.id,copy.invoice_line_item.invoice rescue "" %></td>
    <td>
      <% if copy.status=="SOLD" && copy.sale_order_line_item %>
      <%= copy.sale_order_line_item.sale_order.posted_when %>
      <% end %>
      <br />
      <% if copy.status=="SOLD" && copy.sale_order_line_item %>
      <%= link_to copy.sale_order_line_item.sale_order.id, copy.sale_order_line_item.sale_order %>
      <% end %>
    </td>
 <td class="copy-removed-when">
      <% if copy.status=="RETURNED" && copy.return_order_line_item %>
      <%= copy.return_order_line_item.return_order.posted_when %>
      <% elsif copy.status=="LOST" %>
      <%= copy.deinventoried_when.to_formatted_s(:just_date) %>
      <% end %>
      <br />
      <% if copy.status=="RETURNED" && copy.return_order_line_item %>
      <%= link_to copy.return_order_line_item.return_order.id, copy.return_order_line_item.return_order %>
      <% end %>
    </td>

    <td>
      <%= mylinkbutton "<i class='fa fa-pencil'></i> Edit", edit_copy_path(copy),{},"btn-mini"   if can? :edit, Copy %>
    </td>
    <td>
      <%= mypostlinkbutton "<i class='fa fa-exclamation-circle-sign'></i> Mark lost", mark_lost_copy_path(copy),{:remote=>true},{},"btn-mini copy-mark-lost"  if (copy.status=="STOCK" && (can? :edit, Copy)) %>
    </td>
  </tr>
<% end %>
</table>

app/views/copies/mark_lost.js.erb
$("#copy_<%= @copy.id %> .copy-status").html("<%= escape_javascript(@copy.status) %>")
$("#copy_<%= @copy.id %> .copy-removed-when").html("<%= escape_javascript(@copy.deinventoried_when.to_formatted_s(:just_date)) %>")
$("#copy_<%= @copy.id %> .copy-mark-lost").remove()
$("#copy_<%= @copy.id %> ").effect("highlight")

app/views/copies/new.html.erb
<h1>New copy</h1>

<%= render 'form' %>

<%= link_to 'Back', copies_path %>

app/views/copies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Edition:</b>
  <%= link_to "#{@copy.edition.title.title} #{@copy.edition.number} #{@copy.edition}", @copy.edition %>
</p>

<p>
  <b>Cost:</b>
  <%= @copy.cost %>
</p>

<p>
  <b>Price:</b>
  <%= @copy.price %>
</p>

<p>
  <b>Notes:</b>
  <%= @copy.notes %>
</p>


<p>
  <b>Owner:</b>
  <%= @copy.owner %>
</p>

<p>
  <b>Is used:</b>
  <%= @copy.is_used %>
</p>


<%= link_to 'Edit', edit_copy_path(@copy) %> |
<%= link_to 'Back', copies_path %>