config/routes.rb
Borges::Application.routes.draw do


#  if Rails.env.development?
#    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
#  end


  get "/graphql", to: "graphql#execute"
  post "/graphql", to: "graphql#execute"

  get "/publish", to: "graphql#publish"
  
  resources :text_fragments


  resources :inventory_copy_confirmations do 
    member do
      post :probablyreturned
    end
  end


  resources :inventories do
    member do 
      get :section
      get :bestsellers
      get :owner
      post :fill
      post :fill_books
    end
  end

  resources :event_shifts


  resources :event_staffers do
    get :autocomplete_event_staffer_name, :on => :collection
  end

  get '/events/:id'=> 'events#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :events do 
    get :autocomplete_event_location_title, :on => :collection
  end


  resources :event_locations


  resources :category_title_list_memberships


  resources :sale_order_line_items

 
  resources :sale_orders do
    member do
      post :post
    end
  end

  resources :return_order_line_items

 
  resources :return_orders do
    member do
      post :post
    end

  end



  resources :owners do
    get :autocomplete_owner_name, :on => :collection
  end


  resources :title_category_memberships


  get '/categories/:id'=> 'categories#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :categories do 
    member do 
      get :chart
    end
  end

  resources :post_title_list_links


  resources :post_title_links


  resources :create_post_title_links


  resources :post_categories

  resources :posts

  resources :title_list_memberships


  resources :title_lists do 
    get :autocomplete_title_title, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
  end


  resources :images


#  mount Ckeditor::Engine => '/ckeditor'

  resources :pages  do 
    get :autocomplete_parent_title, :on => :collection
  end


  resources :publishers do 
    member do
      put :merge_editions_from
    end
  end


  resources :customers do 
    get :autocomplete_customer_name, :on => :collection
  end


  resources :distributors do
    member do
      put :merge_orders_from
      get :chart
    end
  end



  resources :invoice_line_items

  get 'invoices/chart' => 'invoices#chart'
  resources :invoices do
    member do
      post :receive
    end
  end


  resources :purchase_order_line_items do 
    member do
      get :hidden_actions 
      put :move_to_purchase_order
      put :copy_to_bucket
      post :cancel
    end
  end

  resources :bucket_line_items do 

    member do
      get :hidden_actions 
      put :copy_to_purchase_order
      put :copy_to_bucket
      put :move_to_bucket
    end
  end



  resources :purchase_orders do 
    member do
      get :hidden_actions 
      post :submit
      post :receive
      post :cancel
      put :smartdestroy
    end
    get :autocomplete_distributor_name, :on => :collection
    resources :purchase_order_line_items
  end

  resources :buckets do 
    member do
      get :hidden_actions 
      put :smartdestroy
    end
    resources :bucket_line_items
  end



  resources :copies do 
    get :autocomplete,:on => :collection
    get :inventory_autocomplete,:on => :collection
    member do
      post :mark_lost
    end

  end


  resources :editions do
    resources :copies
    get :autocomplete,:on => :collection
    get :autocomplete_title_title, :on => :collection
    member do
      get :hidden_actions 
      put :add_to_purchase_order
      put :add_to_title_list
      put :add_to_bucket
      put :add_to_category
      get :bookshop
    end
  end


  resources :contributions do 
    get :autocomplete_author_full_name, :on => :collection
  end

  get 'titles/search' => 'titles#search'
  get '/titles/:id'=> 'titles#redirector',  :constraints => { :id => /[0-9]+/ }

  resources :titles do 
    get :autocomplete_publisher_name, :on => :collection
    get :autocomplete_distributor_name, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
    get :autocomplete_category_name, :on => :collection

  end


  
  get 'authors/search' => 'authors#search'
  get '/authors/:id'=> 'authors#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :authors

  resources :shopping_carts do
    collection do
      post :garbagecollect
    end
    member do
      post :complete
      post :toggle_pulled
      post :toggle_sold_through
      post :toggle_shipped
      post :toggle_picked_up
      post :toggle_pickup_notify
      post :toggle_is_preorder
      post :toggle_needs_attention
      post :defer
      post :ship
      post :subscribe
    end
  end

  resources :shopping_cart_line_items do
    member do
      post :split
    end
  end
  
  get '/book/:isbn', :to => 'editions#byisbn'
  get '/book/', :to => 'editions#byisbn'

  get '/orderdump', :to => 'sale_orders#dump'
  get '/dashboard/search', :to => 'dashboard#search'
  get '/dashboard/snipcart', :to => 'dashboard#snipcart'
  get '/dashboard/:action', :to => 'dashboard'
  get '/dashboard/', :to => 'dashboard#index'
  get '/content/', :to => 'dashboard#content'
  get '/sales/', :to => 'dashboard#sales'
  get '/simplesales/', :to => 'dashboard#simplesales'
  get '/losses/', :to => 'dashboard#losses'
  get '/events_calendar', :to => 'events#calendar'
  get '/consignment/', :to => 'dashboard#consignment'
  get '/ownerflow/', :to => 'dashboard#ownerflow'
  get '/purchases_by_date_and_owner/', :to => 'dashboard#purchases_by_date_and_owner'
  get '/inventory_value_by_date_and_owner/', :to => 'dashboard#inventory_value_by_date_and_owner'
  get '/inventory_report_by_owner/', :to => 'dashboard#inventory_report_by_owner'
  get '/daily/', :to => 'dashboard#daily', :as => "daily"
  get '/manage_calendar/', :to => 'dashboard#manage_calendar'
  get '/books/', :to => 'home#books'
  get '/food/', :to => 'home#food'
  get '/comingsoon/', :to => 'home#comingsoon'
  get '/gcl/', :to => redirect("https://www.threadcoffee.com/greenmount-coffee-lab/")
  get '/coffee/', :to => 'home#coffee'
  get '/orderfoodonline/', :to => 'home#orderfoodonline'
  get '/thread/', :to => 'home#thread'
  get '/blog/', :to => 'posts#index'
  get '/about/', :to => 'home#about'
  get '/2640/', :to => 'events#twentysixforty'
  get '/newsletter/', :to => 'home#newsletter'
  get '/promotion/antifa', :to => 'home#promotion'
  get '/pages/about/', :to => 'home#about'
  get '/cart', :to => "shopping_carts#current"
  get '/shopping_cart_success', :to => "shopping_carts#success"
  post '/webhook', :to => "shopping_carts#webhook"
  post "/create_bli_from_webhook", :to => "bucket_line_items#create_from_webhook"
  put '/update_cart', :to => "shopping_carts#update_current"
  put '/create-checkout-session', :to => "shopping_carts#checkout"
  match '/bookfair' => 'event_locations#show',:defaults => {:id => 4}
  authenticated :user do
    root :to=>'home#frontpage' 
  end
  root :to=>'home#frontpage' 

  devise_for :users
  resources :users
end

app/models/inventory_copy_confirmation.rb
class InventoryCopyConfirmation < ActiveRecord::Base
  belongs_to :inventory
  belongs_to :copy
  attr_accessible :status, :inventory_id,:copy_id
  
  validates :copy_id, :uniqueness => { scope: :inventory_id }

end

app/controllers/inventory_copy_confirmations_controller.rb
class InventoryCopyConfirmationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource


  # GET /inventory_copy_confirmations
  # GET /inventory_copy_confirmations.json
  def index
    @inventory_copy_confirmations = InventoryCopyConfirmation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventory_copy_confirmations }
    end
  end

  # GET /inventory_copy_confirmations/1
  # GET /inventory_copy_confirmations/1.json
  def show
    @inventory_copy_confirmation = InventoryCopyConfirmation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory_copy_confirmation }
    end
  end

  # GET /inventory_copy_confirmations/new
  # GET /inventory_copy_confirmations/new.json
  def new
    @inventory_copy_confirmation = InventoryCopyConfirmation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory_copy_confirmation }
    end
  end

  # GET /inventory_copy_confirmations/1/edit
  def edit
    @inventory_copy_confirmation = InventoryCopyConfirmation.find(params[:id])
  end

  # POST /inventory_copy_confirmations
  # POST /inventory_copy_confirmations.json
  def create
    @inventory_copy_confirmation = InventoryCopyConfirmation.new(params[:inventory_copy_confirmation])
    @inventory_copy_confirmation.status=true
    respond_to do |format|
      if @inventory_copy_confirmation.save
        format.html { redirect_to @inventory_copy_confirmation, notice: 'Inventory copy confirmation was successfully created.' }
        format.json { render json: @inventory_copy_confirmation, status: :created, location: @inventory_copy_confirmation }
        format.js {}
      else
        format.html { render action: "new" }
        format.json { render json: @inventory_copy_confirmation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventory_copy_confirmations/1
  # PUT /inventory_copy_confirmations/1.json
  def update
    @inventory_copy_confirmation = InventoryCopyConfirmation.find(params[:id])

    respond_to do |format|
      if @inventory_copy_confirmation.update_attributes(params[:inventory_copy_confirmation])
        format.html { redirect_to @inventory_copy_confirmation, notice: 'Inventory copy confirmation was successfully updated.' }
        format.json { head :no_content }
        format.js {}
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory_copy_confirmation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_copy_confirmations/1
  # DELETE /inventory_copy_confirmations/1.json
  def destroy
    @inventory_copy_confirmation = InventoryCopyConfirmation.find(params[:id])
    @inventory_copy_confirmation_id =    @inventory_copy_confirmation.id
    @inventory=@inventory_copy_confirmation.inventory
    
    # mark the copy as lost

    @inventory_copy_confirmation.copy.mark_lost()

    # delete the confirmation
    @inventory_copy_confirmation.destroy

    respond_to do |format|
      format.html { redirect_to inventory_copy_confirmations_url }
      format.json { head :no_content }
      format.js {}
    end
  end

  def probablyreturned
    @inventory_copy_confirmation = InventoryCopyConfirmation.find(params[:id])
    @inventory_copy_confirmation_id = @inventory_copy_confirmation.id
    @inventory=@inventory_copy_confirmation.inventory
    

    @inventory_copy_confirmation.copy.mark_probablyreturned()

    # delete the confirmation
    @inventory_copy_confirmation.destroy

    respond_to do |format|
      format.html { redirect_to inventory_copy_confirmations_url }
      format.json { head :no_content }
      format.js {}
    end
  end


end

app/helpers/inventory_copy_confirmations_helper.rb
module InventoryCopyConfirmationsHelper
end

app/views/inventory_copy_confirmations/_form.html.erb
<%= form_for(@inventory_copy_confirmation) do |f| %>
  <% if @inventory_copy_confirmation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_copy_confirmation.errors.count, "error") %> prohibited this inventory_copy_confirmation from being saved:</h2>

      <ul>
      <% @inventory_copy_confirmation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inventory %><br />
    <%= f.text_field :inventory %>
  </div>
  <div class="field">
    <%= f.label :copy %><br />
    <%= f.text_field :copy %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_copy_confirmations/_inventory_copy_confirmation.html.erb
<tr id="inventory_copy_confirmation_<%= inventory_copy_confirmation.id %>" >
  <td><%= link_to inventory_copy_confirmation.copy.edition.title.title, inventory_copy_confirmation.copy.edition, :target=>"blank" %> <small>(Copy #<%= inventory_copy_confirmation.copy.id%>, priced at $<%= inventory_copy_confirmation.copy.price %>, from <%= link_to(inventory_copy_confirmation.copy.invoice.distributor.name, inventory_copy_confirmation.copy.invoice.distributor) rescue "???" %>)</small></td>
  <td><%= inventory_copy_confirmation.copy.edition.isbn %></td> 
  <td >
    <%= form_for(inventory_copy_confirmation, :remote=>true) do |f| %>
    <%= 
    content_tag(:div,
          f.check_box(:status),
          {:class=>"switch switch-inventory","data-on"=>"success","data-off"=>"danger","data-on-label"=>"HERE","data-off-label"=>"GONE"})
    %>
    <div class="inventory_trash">
      <%= link_to raw('<i class="fa fa-trash"></i>'),inventory_copy_confirmation_path(inventory_copy_confirmation),:method=>:delete,:remote=>true,:style=>"#{'display:none' if inventory_copy_confirmation.status}" %>
      <%= link_to raw('<i class="fa fa-backward"></i>'),probablyreturned_inventory_copy_confirmation_path(inventory_copy_confirmation),:method=>:post,:remote=>true,:style=>"#{'display:none' if inventory_copy_confirmation.status}" %>
    </div>
    <% end %>
  </td>
  <td>
    <small><%= sanitize category_status( inventory_copy_confirmation.copy.edition.title)%></small>
    <%= link_to raw('<i class="fa fa-check-circle-o"></i>'), hidden_actions_edition_path(inventory_copy_confirmation.copy.edition.title.latest_published_edition),  {:remote => true, 'data-toggle' =>  'modal', :role=>'button', 'data-target' => '#modal-window'} unless inventory_copy_confirmation.copy.edition.title.latest_published_edition.nil? %>
  </td>
</tr>

app/views/inventory_copy_confirmations/create.js.erb
$("#inventory_copy_confirmations tr:first-child").after("<%= escape_javascript(render :partial=>"inventory_copy_confirmation",:object => @inventory_copy_confirmation) %>");
$("#item").val("");
//$("#item").autocomplete( "option", "minLength",5);
//$("#item").autocomplete( "option", "delay",300);
$("#inventory_copy_confirmation_<%= @inventory_copy_confirmation.id %> .switch").bootstrapSwitch();
$("#inventory_copy_confirmation_<%= @inventory_copy_confirmation.id %>").effect("highlight");
$("#inventory_section_copy_<%= @inventory_copy_confirmation.copy.id %>").hide("fade");

app/views/inventory_copy_confirmations/destroy.js.erb
$("#inventory_copy_confirmation_<%= @inventory_copy_confirmation_id %>").remove();
$("#inventory_copy_confirmations").effect("highlight");

app/views/inventory_copy_confirmations/edit.html.erb
<h1>Editing inventory_copy_confirmation</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_copy_confirmation %> |
<%= link_to 'Back', inventory_copy_confirmations_path %>

app/views/inventory_copy_confirmations/index.html.erb
<h1>Listing inventory_copy_confirmations</h1>

<table>
  <tr>
    <th>Inventory</th>
    <th>Copy</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventory_copy_confirmations.each do |inventory_copy_confirmation| %>
  <tr>
    <td><%= inventory_copy_confirmation.inventory %></td>
    <td><%= inventory_copy_confirmation.copy %></td>
    <td><%= inventory_copy_confirmation.status %></td>
    <td><%= link_to 'Show', inventory_copy_confirmation %></td>
    <td><%= link_to 'Edit', edit_inventory_copy_confirmation_path(inventory_copy_confirmation) %></td>
    <td><%= link_to 'Destroy', inventory_copy_confirmation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inventory copy confirmation', new_inventory_copy_confirmation_path %>

app/views/inventory_copy_confirmations/new.html.erb
<h1>New inventory_copy_confirmation</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_copy_confirmations_path %>

app/views/inventory_copy_confirmations/probablyreturned.js.erb
$("#inventory_copy_confirmation_<%= @inventory_copy_confirmation_id %>").remove();
$("#inventory_copy_confirmations").effect("highlight");

app/views/inventory_copy_confirmations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Inventory:</b>
  <%= @inventory_copy_confirmation.inventory %>
</p>

<p>
  <b>Copy:</b>
  <%= @inventory_copy_confirmation.copy %>
</p>

<p>
  <b>Status:</b>
  <%= @inventory_copy_confirmation.status %>
</p>


<%= link_to 'Edit', edit_inventory_copy_confirmation_path(@inventory_copy_confirmation) %> |
<%= link_to 'Back', inventory_copy_confirmations_path %>

app/views/inventory_copy_confirmations/update.js.erb
$("#inventory_copy_confirmation_<%= @inventory_copy_confirmation.id %>").effect("highlight");