config/routes.rb
Borges::Application.routes.draw do


#  if Rails.env.development?
#    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
#  end


  get "/graphql", to: "graphql#execute"
  post "/graphql", to: "graphql#execute"

  get "/publish", to: "graphql#publish"
  
  resources :text_fragments


  resources :inventory_copy_confirmations do 
    member do
      post :probablyreturned
    end
  end


  resources :inventories do
    member do 
      get :section
      get :bestsellers
      get :owner
      post :fill
      post :fill_books
    end
  end

  resources :event_shifts


  resources :event_staffers do
    get :autocomplete_event_staffer_name, :on => :collection
  end

  get '/events/:id'=> 'events#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :events do 
    get :autocomplete_event_location_title, :on => :collection
  end


  resources :event_locations


  resources :category_title_list_memberships


  resources :sale_order_line_items

 
  resources :sale_orders do
    member do
      post :post
    end
  end

  resources :return_order_line_items

 
  resources :return_orders do
    member do
      post :post
    end

  end



  resources :owners do
    get :autocomplete_owner_name, :on => :collection
  end


  resources :title_category_memberships


  get '/categories/:id'=> 'categories#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :categories do 
    member do 
      get :chart
    end
  end

  resources :post_title_list_links


  resources :post_title_links


  resources :create_post_title_links


  resources :post_categories

  resources :posts

  resources :title_list_memberships


  resources :title_lists do 
    get :autocomplete_title_title, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
  end


  resources :images


#  mount Ckeditor::Engine => '/ckeditor'

  resources :pages  do 
    get :autocomplete_parent_title, :on => :collection
  end


  resources :publishers do 
    member do
      put :merge_editions_from
    end
  end


  resources :customers do 
    get :autocomplete_customer_name, :on => :collection
  end


  resources :distributors do
    member do
      put :merge_orders_from
      get :chart
    end
  end



  resources :invoice_line_items

  get 'invoices/chart' => 'invoices#chart'
  resources :invoices do
    member do
      post :receive
    end
  end


  resources :purchase_order_line_items do 
    member do
      get :hidden_actions 
      put :move_to_purchase_order
      put :copy_to_bucket
      post :cancel
    end
  end

  resources :bucket_line_items do 

    member do
      get :hidden_actions 
      put :copy_to_purchase_order
      put :copy_to_bucket
      put :move_to_bucket
    end
  end



  resources :purchase_orders do 
    member do
      get :hidden_actions 
      post :submit
      post :receive
      post :cancel
      put :smartdestroy
    end
    get :autocomplete_distributor_name, :on => :collection
    resources :purchase_order_line_items
  end

  resources :buckets do 
    member do
      get :hidden_actions 
      put :smartdestroy
    end
    resources :bucket_line_items
  end



  resources :copies do 
    get :autocomplete,:on => :collection
    get :inventory_autocomplete,:on => :collection
    member do
      post :mark_lost
    end

  end


  resources :editions do
    resources :copies
    get :autocomplete,:on => :collection
    get :autocomplete_title_title, :on => :collection
    member do
      get :hidden_actions 
      put :add_to_purchase_order
      put :add_to_title_list
      put :add_to_bucket
      put :add_to_category
      get :bookshop
    end
  end


  resources :contributions do 
    get :autocomplete_author_full_name, :on => :collection
  end

  get 'titles/search' => 'titles#search'
  get '/titles/:id'=> 'titles#redirector',  :constraints => { :id => /[0-9]+/ }

  resources :titles do 
    get :autocomplete_publisher_name, :on => :collection
    get :autocomplete_distributor_name, :on => :collection
    get :autocomplete_title_list_name, :on => :collection
    get :autocomplete_category_name, :on => :collection

  end


  
  get 'authors/search' => 'authors#search'
  get '/authors/:id'=> 'authors#redirector',  :constraints => { :id => /[0-9]+/ }
  resources :authors

  resources :shopping_carts do
    collection do
      post :garbagecollect
    end
    member do
      post :complete
      post :toggle_pulled
      post :toggle_sold_through
      post :toggle_shipped
      post :toggle_picked_up
      post :toggle_pickup_notify
      post :toggle_is_preorder
      post :toggle_needs_attention
      post :defer
      post :ship
      post :subscribe
    end
  end

  resources :shopping_cart_line_items do
    member do
      post :split
    end
  end
  
  get '/book/:isbn', :to => 'editions#byisbn'
  get '/book/', :to => 'editions#byisbn'

  get '/orderdump', :to => 'sale_orders#dump'
  get '/dashboard/search', :to => 'dashboard#search'
  get '/dashboard/snipcart', :to => 'dashboard#snipcart'
  get '/dashboard/:action', :to => 'dashboard'
  get '/dashboard/', :to => 'dashboard#index'
  get '/content/', :to => 'dashboard#content'
  get '/sales/', :to => 'dashboard#sales'
  get '/simplesales/', :to => 'dashboard#simplesales'
  get '/losses/', :to => 'dashboard#losses'
  get '/events_calendar', :to => 'events#calendar'
  get '/consignment/', :to => 'dashboard#consignment'
  get '/ownerflow/', :to => 'dashboard#ownerflow'
  get '/purchases_by_date_and_owner/', :to => 'dashboard#purchases_by_date_and_owner'
  get '/inventory_value_by_date_and_owner/', :to => 'dashboard#inventory_value_by_date_and_owner'
  get '/inventory_report_by_owner/', :to => 'dashboard#inventory_report_by_owner'
  get '/daily/', :to => 'dashboard#daily', :as => "daily"
  get '/manage_calendar/', :to => 'dashboard#manage_calendar'
  get '/books/', :to => 'home#books'
  get '/food/', :to => 'home#food'
  get '/comingsoon/', :to => 'home#comingsoon'
  get '/gcl/', :to => redirect("https://www.threadcoffee.com/greenmount-coffee-lab/")
  get '/coffee/', :to => 'home#coffee'
  get '/orderfoodonline/', :to => 'home#orderfoodonline'
  get '/thread/', :to => 'home#thread'
  get '/blog/', :to => 'posts#index'
  get '/about/', :to => 'home#about'
  get '/2640/', :to => 'events#twentysixforty'
  get '/newsletter/', :to => 'home#newsletter'
  get '/promotion/antifa', :to => 'home#promotion'
  get '/pages/about/', :to => 'home#about'
  get '/cart', :to => "shopping_carts#current"
  get '/shopping_cart_success', :to => "shopping_carts#success"
  post '/webhook', :to => "shopping_carts#webhook"
  post "/create_bli_from_webhook", :to => "bucket_line_items#create_from_webhook"
  put '/update_cart', :to => "shopping_carts#update_current"
  put '/create-checkout-session', :to => "shopping_carts#checkout"
  match '/bookfair' => 'event_locations#show',:defaults => {:id => 4}
  authenticated :user do
    root :to=>'home#frontpage' 
  end
  root :to=>'home#frontpage' 

  devise_for :users
  resources :users
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :image, :name,:remote_image_url, :category_title_list_memberships_attributes
  has_many :title_category_memberships
  has_many :titles,:through => :title_category_memberships


  has_many :category_title_list_memberships
  has_many :title_lists, :through => :category_title_list_memberships
  accepts_nested_attributes_for :category_title_list_memberships, :allow_destroy => true  

  mount_uploader :image, ImageUploader

  after_save :delete_gatsby_cache

  def delete_gatsby_cache
    Rails.cache.delete("gatsby-graphql")
  end

  
  def slug
    name.downcase.gsub(/[^a-z0-9]+/, "-").gsub(/-$/,"")  
  end

  def to_param
    "#{id}-#{slug}"
  end


  def titles_in_stock
    Rails.cache.fetch("/category/#{id}/titles_in_stock", :expires_in => 12.hours) do
      titles.find_all {|t| t.in_stock > 0 }.length
    end
  end
  
  def copies_sold
    Rails.cache.fetch("/category/#{id}/copies_sold", :expires_in => 12.hours) do
      titles.inject(0) {|sum,t| sum + t.sold}
    end
  end
  

  def total_titles
    titles.length
  end
  
  def to_s
    name
  end
  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :hack_out_params, :only=>[:create,:update]
  before_filter :authenticate_user!, :except=>[:show,:index,:redirector] 
  
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order("name asc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  def redirector 
    @category = Category.find(params[:id])
    redirect_to @category
  end


  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  def chart
    @category = Category.find(params[:id])
    @title_info=@category.titles.collect {|t| t}.uniq.collect {|t| {:instock=>t.in_stock > 0,:title=>t.title.gsub(/[^0-9a-z ]/i,""),:average_time_on_shelf=>t.average_time_on_shelf,:profit_to_date=>t.net_profit_or_loss.cents/100,:id=>t.id}}
    @instock=@title_info.find_all {|t| t[:instock]}
    @outofstock=@title_info.find_all {|t| ! t[:instock]}
    respond_to do |format|
      format.html { render action: "chart" }
    end

  end



  private
  def hack_out_params
    unless params[:category][:category_title_list_memberships_attributes].nil?
      params[:category][:category_title_list_memberships_attributes].each do |k,v| 
        params[:category][:category_title_list_memberships_attributes][k].delete :title_list
      end
    end
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= nested_form_for(@category,:html=>{:class=>"form-horizontal"}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= mytextfield f,:name,:name,{:class=>"input-xxlarge"} %>
  <%= mytextarea f,:description,:description %>

  <div class="field control-group">
    <%= f.label :image,:class=>"control-label" %>
    <div class="controls">
      <%= f.file_field :image %>
      <%= image_tag f.object.image_url, {:width=>"30%"} unless f.object.image_url.blank? %> 
    </div>
    <%= mytextfield f,:remote_image_url,:remote_image_url %>
  </div>

  <div class="field control-group">
    <%= f.label :lists_in_this_category, :class=>"control-label" %><br />
    <div class="controls">
      <%= f.fields_for :category_title_list_memberships do |member_form| %>
      <%= myselectfield member_form,:title_list,:name,autocomplete_title_list_name_titles_path,new_title_list_path %>
      <%= myselector member_form,:position,:position,(1..20) %>
      <% end %>
      <div class="verticaloffset">
	<%= f.link_to_add raw("<i class='fa fa-plus-circle'></i> Add to a list"), :category_title_list_memberships, {:class=>:btn} %>
      </div>
    </div>
  </div>


 
  <%= mysubmit f,:save%>

<% end %>

app/views/categories/chart.html.erb
<h1>Average time on shelves vs. profit to date for titles for <%= @category.name %></h1>
<button style="float:right" class="btn" onclick="window.myChart.resetZoom();">Reset zoom</button>
<canvas id="myChart" width="100%" height="50%" style="height:80% !important;"></canvas>


2


<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'scatter',
    data: {
	instocklabels: [<%=  raw @instock.collect {|t| "'#{t[:title]} [#{t[:id]}]'"}.join(", ") %>],
	instockids: [<%=  raw @instock.collect {|t| t[:id]}.join(", ") %>],
	outofstocklabels: [<%=  raw @outofstock.collect {|t| "'#{t[:title]} [#{t[:id]}]'"}.join(", ") %>],
	outofstockids: [<%=  raw @outofstock.collect {|t| t[:id]}.join(", ") %>],
	datasets: [
	    {label: "Titles in stock",
	     backgroundColor: 'rgba(30,255,30,0.5)',
	     data: [ <%=  raw @instock.collect {|t| "{x: #{t[:average_time_on_shelf]},y: #{t[:profit_to_date]}}"}.join "," %>]},
	    {label: "Titles out of stock",
	     backgroundColor: 'rgba(255,30,30,0.5)',
	    data: [ <%=  raw @outofstock.collect {|t| "{x: #{t[:average_time_on_shelf]},y: #{t[:profit_to_date]}}"}.join "," %>]}
	    
		   
		   ,]
    },
    options: {
	onClick: (evt, item) => {
	    e = item[0];
	    if(e._datasetIndex == 0) {
		window.open("/titles/"+myChart.data.instockids[e._index]);}
	    else{
		window.open("/titles/"+myChart.data.outofstockids[e._index]);}
},
	plugins: {
            zoom: {
                // Container for pan options
                pan: {
                    // Boolean to enable panning
                    enabled: true,
		    
                    // Panning directions. Remove the appropriate direction to disable 
                    // Eg. 'y' would only allow panning in the y direction
                    mode: 'xy'
                },

                // Container for zoom options
                zoom: {
                    // Boolean to enable zooming
                    enabled: true,
		    drag:true,
                    // Zooming directions. Remove the appropriate direction to disable 
                    // Eg. 'y' would only allow zooming in the y direction
                    mode: 'xy',
                }
            }
        },
	tooltips: {
	    callbacks: {
		label: function(tooltipItem, data) {
		    var label;
		    if(tooltipItem.datasetIndex == 0) {
			label = data.instocklabels[tooltipItem.index];}
		    else {
			label = data.outofstocklabels[tooltipItem.index];
		    }
		    return label;
		}
	    }
	} ,
        scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom',
		scaleLabel: {
		    display: true,
		    labelString: "Days on shelf"
		}
	    }],
	    yAxes: [{
                type: 'linear',
                position: 'left',
		scaleLabel: {
		    display: true,
		    labelString: "Profit to date"
		}
            }]

	    
        }
    }
});
    

</script>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="row">
<div class="span8">
  <h1>Listing categories</h1>

  <table class="table">
    <tr>
      <th>Name</th>
      <th>Books sold</th>
      <th>Titles in stock</th>
      <th>Total titles</th>
    </tr>
    
    <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name,category %></td>
      <td><%= category.copies_sold %></td>
      <td><%= category.titles_in_stock %></td>
      <td><%= category.total_titles %></td>
  </tr>
    <% end %>
</table>
</div>
  
<div class="span4">
<%= mylinkbutton 'New Category', new_category_path if can? :edit,Category%>
</div>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% content_for :title do%>
     <%= @category.name %>
<% end %>

<% content_for :og do%>
<% begin %>
<meta property="og:image" content="https://redemmas.org/<%= @category.image.url %>" />
<% rescue %>

<% end %>
<% end %>



<% content_for :description do%><%= @category.description %><% end %>

<% if @category.image.nil? %>

<div class="container-fluid">
  <div class="row spaceontop">
  <div class="col-xs-offset-1 col-xs-10">
    <h1 class="posttitle">Category:    <%= @category.name %></h1>
  </div>
</div>

<% else %>

<div class="row post_titlesplash <%= 'post-has-image' if @category.image %>" 
     style="background:linear-gradient(
	    rgba(20,0,0, 0.2), 
	    rgba(20,0,0, 0.2)
	    ),url(<%= @category.image.url %>);background-attachment:fixed; 
	    background-size:cover;margin-bottom:0px;">
  <div class="col-xs-12 col-sm-offset-1 col-sm-7">
    <h1 class="posttitle">Section: <%= @category.name %></h1>
  </div>
  <div class="col-xs-12 col-sm-4  ">
    <%= theme_partial :social %>
    <%= mylinkbutton 'Edit', edit_category_path(@category) if can? :edit,Category %>
  </div>
  </div>

<% end %>


<div class="container-fluid">
  <div class="row spaceontop">
    <p id="notice"><%= notice %></p>
    
    <div class="col-xs-12">
      <div style="float:right;">
	<%= mylinkbutton 'Edit', edit_category_path(@category) if can? :edit,Category %>
	<%= mylinkbutton 'Analyze titles for profitability', chart_category_path(@category), {},"btn-success btn-large"  if can? :edit,Category %>
	
      </div>  
      <div class="introduction">
	<%= sanitize @category.description %>
      </div>
    </div>
  </div>
  
  <hr />
  
  
  
  <div class="row">
    <% if @category.title_lists.where(:public=>true).length > 0 %>
    <h2 class="related" style="clear:both;">Featured lists</h2>
  </div>
  <% @category.title_lists.order("position ASC").each do |tl| %>
  <h3 class="relatedsubhead"><%= link_to tl.name,tl %></h3>
  <div class="introduction"><%= sanitize tl.description %></div>
  <div class="row">
    <% cache("category-tl#{tl.id}", :expires_in => 120.minutes) do %>
    <%= make_a_grid_from_titles usefully_sorted(tl.titles).first(5) %>
    <% end %>
    <div class="col-xs-6 col-sm-4 col-md-2 gridmore">
      <%= link_to "More titles on this list »",tl %>
    </div>
  </div>
  <% end %>
  <% end %>
  
  
  <% if @category.titles.length >0 %>
  <h2 class="related" style="clear:both;">All titles in this section</h2>
  <div class="row">  
    <% cache("category-#{@category.id}", :expires_in => 120.minutes) do %>
    <%= make_a_grid_from_titles(@category.titles.order("title asc")) %>
    <% end %>
  </div>
  <% end %>
</div>
</div>
<%= render "/titles/searchbrowse" %>